### ISSUE TITLE
transport.rest is deprecated

### ISSUE THREAD

**Issue by derhuerst** [deg0nz/MMM-PublicTransportBerlin#14]
Hey! This is the author of [vbb-rest](https://github.com/derhuerst/vbb-rest), deployed at `transport.rest`. Nice to see that you (seem to) use my service!

I'm here to let you know that **The API & format deployed at `transport.rest` is deprecated. Please use the new API, deployed at `vbb.transport.rest`.** You can find docs for the new format in the [`vbb-rest` repo](https://github.com/derhuerst/vbb-rest).

**Comment by deg0nz** [comment]
Hey, @derhuerst

Thx for the info! When will the old service stop working?

**Comment by derhuerst** [comment]
@deg0nz I put an error in place on every fifth response to let people know (unfortunately I failed to build a proper mechanism up front).  I will remove that again soon and keep it running for about a month. Keep in mind that `transport.rest` may now contain outdated data, as the [static modules](https://github.com/derhuerst/vbb-modules/blob/2b3bb2d/readme.md#static-data) is relies on are outdated.

**Comment by derhuerst** [comment]
FYI: I will shut off `transport.rest` in a week. See also https://github.com/deg0nz/MMM-PublicTransportBerlin/issues/15#issuecomment-306840657

**Comment by deg0nz** [comment]
Added support for `vbb-client@2.0.0` in c82d4b0.

**Comment by derhuerst** [comment]
Will shut off the old endpoint on Friday.

**Comment by derhuerst** [comment]
Will shut it off now.

**Comment by deg0nz** [comment]
Thanx again for the info!
Vbb-client V.2.0.1 is supported by my module and it's working fine.

The users have to update their modules if they encounter errors..
