### ISSUE TITLE
Module is not showing anymore

### ISSUE THREAD

**Issue by M1dn8** [deg0nz/MMM-PublicTransportBerlin#15]
Hey there,

after I installed my MM-config completly new, the MMM-PublicTransportBerlin won't load anymore.
Before all was fine...can everybody help me or have the same problem?

thx

**Comment by rejas** [comment]
Any logs or errors you can provide? Or your config file?

**Comment by M1dn8** [comment]
Hey rejas,
thx for ur answer.

So sry no errors or untypical in the logs.

I think my config is fine, cause the mm is starting and the module show "Laden". I try the dafault config too but same bug. Maybe something change in the way the module works?!

Here is my config

{
                        module: 'MMM-PublicTransportBerlin',
                        position: 'bottom_right',
			//classes: 'default',
                        config: {
                            	name: "Hannes-Meyer-Straße",
				//stationId: 900000230207
				}
	        },

No one has the same Error?!

**Comment by rejas** [comment]
What node version are you running?

**Comment by rejas** [comment]
Reason I ask is because I dont have problems with your config on my raspberry (with node6) but with Node8 on my mac I dont get beyond the "laden" message neither (and logs show this:
`
(node:42964) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'type' of undefined
(node:42964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by rejas** [comment]
Well, cant be node.js, can reproduce it on node6.10.3.

**Comment by rejas** [comment]
Mmmmhhhh... further inspecting the code I see that the VBBFetcher.fetchDepartures gets data that is different than what processData later on expects. The field "product" is nowhere to be found in the data fetched from the vbb-client yet it is referenced a few times (and triggers the error therefor):
`!this.config.excludedTransportationTypes.includes(row.product.type.type))`
and
`
                line: row.product.line,
                nr: row.product.nr,
                type: row.product.type.type,
                color: row.product.type.color,
`

I wonder if something in the vbb-rest-api has changed in the last days (maybe @derhuerst can shed some light on it)?

**Comment by deg0nz** [comment]
Hey guys,
I'm sorry for the bad communication in the last time.
I'm aware of that issue with the data, because @derhuerst said that he would change the api.

Unfortunately I have not much time to do something about it right now.
It's on my schedule for next week some time... So please be a little patient, I'm gonna fix it asap.

If you want, please feel free to send a pull request with a fix, I'd appreciate it ;) If not, I'm gonna try to find time next week :)

**Comment by rejas** [comment]
You got any links for the info on what changed? Maybe I find some time this week :-)

**Comment by M1dn8** [comment]
hey guys,

really thank u gor ur help 👍🏼

I read about the changes yesterday here https://github.com/deg0nz/MMM-PublicTransportBerlin/issues/14
So but I'm not so cool with all this stuff...so very happy to hear that u will fix it...it's one of the main functions on my mm so very thank u!

Greats

**Comment by derhuerst** [comment]
You shouldn't use `latest` as the version of `vbb-client`. By doing this, you expose your app to any breaking change occurring in its dependencies. Use the caret symbol (`^`) to express the version you want, e.g. `^1.0.0` in this specific case.

Background: [`vbb-client`](https://github.com/derhuerst/vbb-client#vbb-client) is the client to the public transport API that I provide. It follows [SemVer](http://semver.org). [`vbb-client@^1.0.0`](https://github.com/derhuerst/vbb-client/tree/7d1f1e6da2253b9b18f79dc351e45f76fa46a082) queries the old API at `transport.rest`, whereas `vbb-client@latest` (or rather `vbb-client@^2.0.0`) queries the new API at `vbb.transport.rest`, which returns data in [the *Friendly Public Transport Format*](https://github.com/public-transport/friendly-public-transport-format).

It is considered best practice to you SemVer-compatible version ranges for dependencies. This will fix your app temporarily, until I will shut the server off in about two weeks.

**Comment by rejas** [comment]
That version update explains why my mirror still works, packages were installed pre-2.0.0. Will provide a PR to get it working with v1 for now. Will have alook at the new format later.

**Comment by rejas** [comment]
In the meantime @M1dn8 you can use my branch at https://github.com/rejas/MMM-PublicTransportBerlin/tree/vbb_client1 to try out your mirror.

**Comment by deg0nz** [comment]
Ok, I Merged PR #16 and pulled the git on my mirror. It seems to work.

As I said, I hope I can start integrating `vbb-client@2.0.0` into `MMM-PublicTransportBerlin` this week.

@M1dn8: Please do a `git pull` in the `MMM-PublicTransportBerlin`-folder on your mirror. (Maybe you need to restart the MM-Application for the changes to take effect) 
If this is working for you, please close this issue :)

**Comment by M1dn8** [comment]
hey guys,

thx all of u for working together to fix this problem! 
And YES it works for now...

Looking forward to see the new update with the new style.

thank you for ur work

greets 

#close for now ;)

**Comment by deg0nz** [comment]
I added support for `vbb-client@2.0.0`. Everything should now work as expected.

Please note, that you should execute `npm install` in the `MMM-PublicTransportBerlin` directory to use version `2.0.0`.
