### ISSUE TITLE
Recognize Tram line colors and show them in the module instead of the red-ish Tram color for all Trams

### ISSUE THREAD

**Issue by deg0nz** [deg0nz/MMM-PublicTransportBerlin#17]
Line colors in SVG images here:
https://en.wikipedia.org/wiki/Trams_in_Berlin

**Comment by derhuerst** [comment]
See also [`vbb-util/lines/colors.json`](https://github.com/derhuerst/vbb-util/blob/master/lines/colors.json). I plan to deprecate this module in the future, but for now, you're fine to use it. 😉

**Comment by deg0nz** [comment]
@derhuerst This is nice, thank you! what will happen, when du deprecate this? Can I access the data elsewhere then?

If not, I'll just build a CSS file for my module out of your JSON...

**Comment by derhuerst** [comment]
Yes, I will (of course) make this machine-readable and easily accessible just as before.

**Comment by deg0nz** [comment]
hey, @foliveira3101!

Thanks for offering your help! Actually, I don't need help with this particular issue. 

I already implemented the functionality with use of [`vbb-line-colors`](https://github.com/derhuerst/vbb-line-colors/). Now, the actual colors for tram and regional are added to the color palette.
I'm currently testing this on my mirror and want to add some error handling. A commit with this feature will follow the next days...

But thanks for asking anyway :)

**Comment by deg0nz** [comment]
Commit 51d0728ffe4d25301398e543e6cb68411f16d5bd implements this feature. Closing now.
