### ISSUE TITLE
Neues Format für Abfahrtzeit

### ISSUE THREAD

**Issue by bertbln** [deg0nz/MMM-PublicTransportBerlin#194]
Kann die Abfahrtzeit wahlweise auch als 'in x Minuten' angezeigt werden?
Bei Zeiten => einer Stunde (Ja, auf dem Lande gibt es sowas...) dann als Uhrzeit.
Also so wie bei DAISY ...

**Comment by deg0nz** [comment]
Theoretisch ist das möglich, aber dann müsste auch das `interval` entsprechend klein gehalten werden (<= 1 min).

Per default holt das Modul alle 2 Minuten neue Daten und aktualisiert sich dann. Bei der Einstellung wäre ein relatives Zeit-Label jeweils im schlechtesten Fall um 1 Minute falsch.

Ich kann das einbauen, kann aber keine leider Zeit versprechen. Falls du es dringend benötigst, kannst du gerne einen PR stellen :)

**Comment by bertbln** [comment]
Hallo,

danke für die schnelle Antwort… 

An diesen Zusammenhang mit dem Intervall habe  ich nicht gedacht. War nur so eine Idee, ist weder dringend noch wichtig. 

Man könnte ja die Zeit bis zur Abfahrt auch intern berechnen und runterzählen, aber das wird dann nur unnötig komplex.

Am besten so lassen wie es ist…

Viele Grüße
Arnulf
