### ISSUE TITLE
Ignore stations close to the original station

### ISSUE THREAD

**Issue by Jopyth** [deg0nz/MMM-PublicTransportBerlin#2]
If a station is close to the original station, the module displays lines which stop at both stations multiple times. Is it possible with the underlying `vbb-hafas` to ignore nearby stations and show departures from the original station only? I.e. if I want to show Departures from Potsdam Hauptbahnhof, ignore departures from Lange Brücke, since many trams stop at both stations, but showing it once is enough.

**Comment by deg0nz** [comment]
Yes, you're right. I'll look into it. Thanks for the PR, by the way :)

**Comment by deg0nz** [comment]
Okay, I see you problem. When I enter Potsdam Hauptbahnhof as station, I get results for "Potsdam Hauptbahnhof Nord" and "Lange Brücke" too.
I can't tell `vbb-hafas` to just get information of one station, but I can filter the results that should be shown on the mirror by the `stationId`.

I'll implement this as default behaviour.

**Comment by deg0nz** [comment]
But I see, that filtering for only one `stationId` leads to loosing different kinds of transportation methods. For example Bus and Tram stations at Alexanderplatz have other station IDs altough they have the same name.

Would it be OK for you, If I provide a possibility to filter the stations you don't want to have in the list? Like a variable  with a list. e.g.:
`ingoreStations = '9300129,837646,1273844'`

**Comment by Jopyth** [comment]
Sounds good, then I can just keep one Tram station, and filter the others.

**Comment by deg0nz** [comment]
@Jopyth: I added the functionality for ignoring stations. Could you please verify is it works for you?

**Comment by Jopyth** [comment]
Thank you! Will do that on Monday.

**Comment by Jopyth** [comment]
Finally was able to test the module. Everything works fine. I will make some modifications to the module, though, mostly visual options. As soon as I am finished I will make a PR, so you can integrate them if you want.
