### ISSUE TITLE
502 error

### ISSUE THREAD

**Issue by Snake16547** [deg0nz/MMM-PublicTransportBerlin#25]
Right now there only 502 errors incoming, that is not really a module problem right?

https://imgur.com/BisDTOU

**Comment by deg0nz** [comment]
Yes, this means that the module is working fine. The data source seems to have problems delivering the data. It's a normal 502 HTTP status code.

You can check the availability of the VBB REST API here:
https://status.transport.rest/ 

(The source, where the module gets is data is "vbb.transport.rest departures")

**Comment by Snake16547** [comment]
thanks!

**Comment by derhuerst** [comment]
**I won't run the public endpoint at `2.vbb.transport.rest` for the time being.** Maybe VBB and I will find a compromise when we meet next week. Refer to derhuerst/vbb-rest#29 for more details.

From the updated `vbb-rest` readme:

> **If you use JavaScript to process the data, use [`vbb-hafas`](https://github.com/derhuerst/vbb-hafas) directly, otherwise host your `vbb-rest` instance for now.**
