### ISSUE TITLE
Add canceled trips function

### ISSUE THREAD

**Issue by deg0nz** [deg0nz/MMM-PublicTransportBerlin#26]
Add canceled trips function to mark canceled trips in the module with strikethrough or  'canceled'-label.

[`hafas-client` v1.3.0](https://github.com/derhuerst/hafas-client/commit/4ee1b27ae61d6923d77bbbb6bf025dc2049eaaef) supports this.

**Comment by derhuerst** [comment]
The changes should be live at `vbb.transport.rest` now. It's hard to test wether everything works though, as only very few departures get canceled.

**Comment by deg0nz** [comment]
Commit 2f80af0 implements this.
