### ISSUE TITLE
vbb.transport.rest is deprecated

### ISSUE THREAD

**Issue by derhuerst** [deg0nz/MMM-PublicTransportBerlin#27]
Hey! This is the author of [vbb-rest](https://github.com/derhuerst/vbb-rest), deployed at `vbb.transport.rest`. Nice to see that [you (seem to) use my service](https://github.com/deg0nz/MMM-PublicTransportBerlin/blob/101eb2ebcb88fad1164950b854eb8e9f6b2a8056/README.md#how-to-get-the-stationid)!

I'm here to let you know that **The API & format deployed at `vbb.transport.rest` is deprecated. Please use the new API, deployed at `2.vbb.transport.rest`.** You can find docs for the new format in the [`vbb-rest` repo](https://github.com/derhuerst/vbb-rest).

**Comment by deg0nz** [comment]
Thanks for the hint! I alway appreciate your nice depcrecation notes. :) So thank you for that!

Since commit a2cb835 the module uses `vbb-client@3.0.1` so the new endpoint uses `2.vbb.transport.rest`. Closing.

**Comment by derhuerst** [comment]
I've shut it off now.

**Comment by derhuerst** [comment]
**I won't run the public endpoint at `2.vbb.transport.rest` for the time being.** Maybe VBB and I will find a compromise when we meet next week. Refer to derhuerst/vbb-rest#29 for more details.

From the updated `vbb-rest` readme:

> **If you use JavaScript to process the data, use [`vbb-hafas`](https://github.com/derhuerst/vbb-hafas) directly, otherwise host your `vbb-rest` instance for now.**

**Comment by derhuerst** [comment]
**I have set up [`v5.vbb.transport.rest`](https://v5.vbb.transport.rest/), the successor of `3.vbb.transport.rest`.** As usual, unfortunately the response format has changed slightly (to the format of [`hafas-client@5`](https://github.com/public-transport/hafas-client/tree/5), make sure to check its [migration guide](https://github.com/public-transport/hafas-client/blob/5/docs/migrating-to-5.md)).

I will keep `3.vbb.transport.rest` running for a while, and announce its shutdown [via RSS](https://transport.rest/feed.xml) before.

**Comment by derhuerst** [comment]
I have deprecated `3.vbb.transport.rest` and will shut it off in a month. Please migrate to [`v5.vbb.transport.rest`](https://v5.vbb.transport.rest/).

**Comment by deg0nz** [comment]
@derhuerst Thanks for the reminder! I migrated to hafas 5.x with commit 658b48c5114f6fc2d6d50174aa55719297642c93

**Comment by derhuerst** [comment]
Just noticed that the deprecation warning is somewhat irrelevant for this project because, unlike a public API endpoint, `hafas-client` versions won't be shut off. You can of course continue using them, but they won't receive bug requests (except explicit requests for backports) and won't have all the new features.

**Comment by deg0nz** [comment]
Oh, Ok... I didn't look into the code of the HAFAS Client and the Profiles. I thought that when I use the corresponding profile, I automatically use the new endpoints with new `hafas-client` versions.

So the updated endpoints and APIs are only in use for the specific clients (e.g. `vbb-hafas` or `bvg-hafas`)?

I already thought about re-migrating to VBB or BVG, because it seems that the VBB-Outage problems are more or less solved by now. I migrated to `hafas-client`to have a more reliable data source back in the day

**Comment by derhuerst** [comment]
Do we have a misunderstanding here? There are a lot of counterintuitive versioning schemes involved here:

- `v5.vbb.transport.rest` is [`vbb-rest#5`](https://github.com/derhuerst/vbb-rest/tree/5), which uses `vbb-hafas@7`, which uses `hafas-client@5` with the VBB profile.
- `3.vbb.transport.rest` is [`vbb-rest#3`](https://github.com/derhuerst/vbb-rest/tree/3), which uses `vbb-hafas@6`, which uses `hafas-client@4` with the VBB profile.
- `v5.bvg.transport.rest` is [`bvg-rest#5`](https://github.com/derhuerst/bvg-rest/tree/5), which uses `bvg-hafas@3`, which uses `hafas-client@5` with the BVG profile.
- `2.bvg.transport.rest` is [`bvg-rest#2`](https://github.com/derhuerst/bvg-rest/tree/2), which uses `bvg-hafas@2`, which uses `hafas-client@4` with the DB profile.

The gist of it is that the `v5.*.transport.rest` use `hafas-client@5` underneath, whereas the previous `transport.rest` APIs (namely `3.vbb` & `2.bvg`) are deprecated now and use `hafas-client@4` underneath.

**Since you use `hafas-client` directly *anyways*, technically, you didn't have to upgrade to `hafas-client@5`**, because `hafas-client@4` will keep working until HaCon breaks the HAFAS endpoints. Now that you have upgraded though, you benefit from bugfixes and additional features in `hafas-client`.

**Comment by derhuerst** [comment]
You don't need to do anything here, except to check that your code works with the `hafas-client@5` response structures.

**Comment by deg0nz** [comment]
Alright. Okay, that is good to know. Was a litte bit confusing tbh...
Thanks fo clarifying!

**Comment by derhuerst** [comment]
Yeah, the reason why I bumped the `transport.rest` APIs from `3`/`2` to `v5` is to make it less confusing: From now on, their version will follow the `hafas-client` version.
