### ISSUE TITLE
Config file error after update

### ISSUE THREAD

**Issue by Wominator** [deg0nz/MMM-PublicTransportBerlin#28]
Hi deng0nz,

great module, great work. I have updated to the new version and also your new entry for the config.js, but I always get the "config file error". Even when I take a blank config.js with just MMM-PublicTransportBerlin and your "Alexanderplatz" entry as a single module. Tried everything, like js-linter and so on, nothing worked out.

Any idea? 

Thanks in advance
wominator

**Comment by rejas** [comment]
Had some trouble updateing too. Two things changed which I had to fix in my config:
a) stationId is now a string (was int before), so add some '...' around it
b) delay got renamed to travelTimeToStation

**Comment by deg0nz** [comment]
Thanks for your hints @rejas!

Yes, due to API changes, the stationId must be a string now (like `'90000010000'` for Alexanderplatz) unfortunately I wasn't able to provide a backwards compatibility for this value...

The `delay` option should still work, but will be removed in a future release, so it's better to change it now to `travelTimeToStation` :)

I'll leave this issue open if more people have these issues.

**Comment by deg0nz** [comment]
@Wominator if you're still experiencing the issue, could you paste your config here?

**Comment by Wominator** [comment]
Hi! 
If I tjust do the suggested changes to my original config, the mirror crashes completly. When I use the following config, I get the mentioned config error.

`/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "de",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
{
    module: 'MMM-PublicTransportBerlin',
    position: 'top_left',
    config: {
        name: 'Alexanderplatz',
        stationId: '90000010000',
        hidden: false,
        ignoredStations: [900000100003,2342,1337],
        ignoredLines: ['U5', 'U8', 'S75' 'Bus 100'],               
        excludedTransportationTypes: 'bus,suburban,subway',   
        travelTimeToStation: 10,
        interval: 120000,
        departureMinutes: 10,          
        maxDepartures: 15,
        marqueeLongDirections: true,
        showColoredLineSymbols: true,  
        useColorForRealtimeInfo: true,
        showTableHeaders: true,
        showTableHeadersAsSymbols: true,
        maxUnreachableDepartures: 3,    
        maxReachableDepartures: 7,
        fadeUnreachableDepartures: true,
        fadeReachableDepartures: true,
        fadePointForReachableDepartures: 0.25,
        excludeDelayFromTimeLabel: true
    }
},
		]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}`

**Comment by Wominator** [comment]
`/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "de",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
{
    module: 'MMM-PublicTransportBerlin',
    position: 'top_left',
    config: {
        name: 'Alexanderplatz',
        stationId: '90000010000',
        hidden: false,
        ignoredStations: [900000100003,2342,1337],
        ignoredLines: ['U5', 'U8', 'S75' 'Bus 100'],               
        excludedTransportationTypes: 'bus,suburban,subway',   
        travelTimeToStation: 10,
        interval: 120000,
        departureMinutes: 10,          
        maxDepartures: 15,
        marqueeLongDirections: true,
        showColoredLineSymbols: true,  
        useColorForRealtimeInfo: true,
        showTableHeaders: true,
        showTableHeadersAsSymbols: true,
        maxUnreachableDepartures: 3,    
        maxReachableDepartures: 7,
        fadeUnreachableDepartures: true,
        fadeReachableDepartures: true,
        fadePointForReachableDepartures: 0.25,
        excludeDelayFromTimeLabel: true
    }
},
		]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}`

**Comment by deg0nz** [comment]
hmm... this is weird. I could imagine, that the last comma behind the `MMM-PublicTransportBerlin` module should be removed.

Did you try the `npm run config:check` command in your MagicMirror folder?

**Comment by Wominator** [comment]
Hi!
Yes, removed the comma, took every separate line out, one by one with //, restartet the mirror, always the same, config  error. When I follow the given instructions, 'stationID' and so on, the screen stays black after restart, without error message.
Unfortunenatly, I installed the module on a mirror for the company, 4 times, for different stations. 
Regards 
Womi

**Comment by Wominator** [comment]
Sorry for being not precise:

"Unfortunenatly, I installed the module on a mirror for the company, 4 times, for different stations." 
It  worked out for several month with 4 instances on a 49 inch mirror, flawless.

**Comment by deg0nz** [comment]
Did you try deleting the `node_modules` folders for the module and the mirror app itself and run `npm install` on both levels again? Sometimes npm breaks things with old versions...

And please check your config with `npm run config:check`in the mirror-folder

**Comment by Wominator** [comment]
I'll double check it later, not at home. I removed the MMM-Public... folder and did a clean install of the new version. No success.
"Npm run..." stops with error "can't access folder / file", latest version of MagicMirror installed.
Regards 
Womi

**Comment by Wominator** [comment]
Hi again. 
I deleted the 'nodes_modules', did a 'git pull && npm install', ran 'npm run config:check', found out, that in the line 'ignoredLines:' a comma was missing. Then I removed everyting within ' [ ] ' ran 'npm run config:check' again. No errors. Restarted MM, output: Black screen without error message.
Then I removed the MMM-Pub.. from config.js, just the clock module enabled, restarted the MM, no ptoblem.
BTW, with or without MMM-Pub... in the config.js the output of 'npm run config:check' is:
'> magicmirror@2.2.2 config:check /home/pi/MagicMirror
> node tests/configs/check_config.js
Checking file...  /home/pi/MagicMirror/config/config.js
Your configuration file doesn't contain syntax errors :)'

Yet any idea? 
Maybe, I'll have the time tomorrow to do a fresh install of the pi & mm. We'll see if this might help.
Regards 
Womi

**Comment by deg0nz** [comment]
Hmmm...

One thing you could try is checking the mirror logs. If you start the mirror app with `pm2`, you can check them with a command like `pm2 logs mm` ( when you configured it as in the MM wiki).

If not, you could accept your pc‘s ip in the IP whitelist of your config and connect to the mirror on port 8080 via browser and use the developer tools of your browser to check the logs.

Maybe that gives you more information about the error.

**Comment by Wominator** [comment]
Hi again!
I uninstalled reinstalled the module again, no the MM starts, but doesn't show the 'MMM-PubilcTransportBerlin' module.

`pm2 logs mm` red part:
`/home/pi/.pm2/logs/mm-error-0.log last 15 lines:
0|mm       |     at Module._compile (module.js:556:32)
0|mm       |     at Object.Module._extensions..js (module.js:565:10)
0|mm       |     at Module.load (module.js:473:32)
0|mm       |     at tryModuleLoad (module.js:432:12)
0|mm       | { Error: Cannot find module 'vbb-client'
0|mm       |     at Module._resolveFilename (module.js:455:15)
0|mm       |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|mm       |     at Function.Module._load (module.js:403:25)
0|mm       |     at Module.require (module.js:483:17)
0|mm       |     at require (internal/module.js:20:19)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-PublicTransportBerlin/VbbFetcher.js:2:19)
0|mm       |     at Module._compile (module.js:556:32)
0|mm       |     at Object.Module._extensions..js (module.js:565:10)
0|mm       |     at Module.load (module.js:473:32)
0|mm       |     at tryModuleLoad (module.js:432:12) code: 'MODULE_NOT_FOUND' }`


the "green part"

`/home/pi/.pm2/logs/mm-out-0.log last 15 lines:
0|mm       |
0|mm       | Starting MagicMirror: v2.2.2
0|mm       | Loading config ...
0|mm       | Loading module helpers ...
0|mm       | No helper found for module: alert.
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: updatenotification
0|mm       | No helper found for module: clock.
0|mm       | No helper found for module: MMM-PublicTransportBerlin.
0|mm       | All module helpers loaded.
0|mm       | Starting server on port 8080 ...
0|mm       | Server started ...
0|mm       | Connecting socket for: updatenotification
0|mm       | Sockets connected & modules started ...
0|mm       | Launching application.`

So, it looks like the Vbbfetcher.js is missing.

Regards 
Womi

**Comment by Wominator** [comment]
Sorry, wrong button.

**Comment by deg0nz** [comment]
The first message says, that `vbb-client` is missing. Did you run `npm install` *in the folder of the `MMM-PublicTransportBerlin` module*?

Also, the line `No helper found for module: MMM-PublicTransportBerlin.` of "the green part" is weird. could you re-check, if all the files from the repository are present? This says, that the module helper is missing....

**Comment by Wominator** [comment]
Hi!
I did a clean install of the module. Ran npm install without errors. I even tried to install the VBB client it self, no success. How can I check, all files are in place?

**Comment by rejas** [comment]
Look into this directory ```MagicMirror/modules/MMM-PublicTransportBerlin/node_modules```: (adjust to where you installed MagicMirror @Wominator )

Mine has those contents including the vbb-client:

```
core-util-is    is-stream            pinkie-promise        through2
encoding        json-stringify-safe  process-nextick-args  util-deprecate
fetch-ponyfill  minimist             readable-stream       vbb-client
iconv-lite      ndjson               safe-buffer           xtend
inherits        node-fetch           split2
isarray         pinkie               string_decoder

```

What does yours contain?

**Comment by Wominator** [comment]
Hi!
So.... After deleting the MMM-Public... folder again, reinstalling the module another time, running npm install, and so on, it works know. Don't know what happend or is different this time. 
Thanks a lot for your support and your patience.

Regards 
Womi

**Comment by deg0nz** [comment]
Okay, I'm glad it finally worked. :)

I'm closing this issue now. If you encounter errors again, feel free to reopen this issue.
