### ISSUE TITLE
TypeError: depArray[(i + 1)] is undefined

### ISSUE THREAD

**Issue by thobach** [deg0nz/MMM-PublicTransportBerlin#3]
Sometimes the following error is shown in the user interface:

TypeError: depArray[(i + 1)] is undefined

I assume this appears when there is just 1 entry, in which case depArray[1], if i = 0, does not exist.

**Comment by deg0nz** [comment]
Thanks for reporting! 
I'll look into this asap.

**Comment by deg0nz** [comment]
Hey, @thobach!
I added a check for that. Could you please pull the latest commit and tell me, if it works for you?

...and maybe you should tweak your `delay` time and your `departureMinutes`  time combinations if there's only one reachable departure in the list/array.

Thanks in advance! 
And a happy new year 2017 ;)

**Comment by deg0nz** [comment]
hey, @thobach, any news?

**Comment by deg0nz** [comment]
No feedback for 1 month now. I assume the error is fixed properly. I'm Closing this issue now. If anyone is still encountering this issue, feel free to reopen it again.
