### ISSUE TITLE
Bus logo shown as undefined with new server host

### ISSUE THREAD

**Issue by ferby09** [deg0nz/MMM-PublicTransportBerlin#33]
After @juliuste 's selfless help regarding the server problem of the last days, I'm encountering the following problem now:
I use the module to see when certain busses and a certain train are departuring. Bus and train have a separate entry in my config. The logo for the U-Bahn is shown as usual but the busses just show a purple background with "undefined" written on it. I still can see the departure time and the destination.
Does anybody else have the same problem with our new host?

**Comment by rejas** [comment]
yes, bus line logos dont show up in my mirror neither since then. can't imagine that @derhuerst changed something though...

**Comment by juliuste** [comment]
I basically `git clone`d [`vbb-rest@2`](https://github.com/derhuerst/vbb-rest/tree/2), the only possible error on "our" side that I could imagine would be if the instance of vbb-rest running on the old server was somehow not exactly identical to branch `@2` on GitHub. @derhuerst could this be the case?

**Comment by ferby09** [comment]
Sure, but I'd need some instructions on how to do that. :P

**Comment by derhuerst** [comment]
Best would be the URL that your magic mirror fetched that data from (including the station and time) and the response. AFAIK magic mirrors are browser-based, so you could use the network inspector for getting the request.

Alternatively, tell me a station ID and a time and I will try to find the reason.

But most likely, the error will be in the displaying code (this repo) anyways.

**Comment by Wominator** [comment]
Hi!
Same issue here. The Station-ID is Friedrich-Wilhelm-Str. / 900000068353

![mm-ptb-fehler](https://user-images.githubusercontent.com/27849722/42134846-331382f0-7d43-11e8-9410-04c3b39f7876.PNG)

Regards
womi

**Comment by derhuerst** [comment]
```curl
curl 'https://2.vbb.transport.rest/stations/900000068353/departures'
```

```json
[
	{
		"journeyId": "1|59206|14|86|1072018",
		"station": {
			"type": "station",
			"id": "900000068353",
			"name": "Friedrich-Wilhelm-Str.",
			"location": {
				"type": "location",
				"latitude": 52.458431,
				"longitude": 13.376129
			},
			"products": {
				"suburban": true,
				"subway": true,
				"tram": true,
				"bus": true,
				"ferry": false,
				"express": false,
				"regional": false
			},
			"lines": [
				{
					"type": "line",
					"id": "bus-184",
					"name": "184",
					"public": true,
					"class": 8,
					"product": "bus",
					"mode": "bus",
					"symbol": null,
					"nr": 184,
					"metro": false,
					"express": false,
					"night": false
				},
				{
					"type": "line",
					"id": "bus-246",
					"name": "246",
					"public": true,
					"class": 8,
					"product": "bus",
					"mode": "bus",
					"symbol": null,
					"nr": 246,
					"metro": false,
					"express": false,
					"night": false
				},
				{
					"type": "line",
					"id": "bus-n84",
					"name": "N84",
					"public": true,
					"class": 8,
					"product": "bus",
					"mode": "bus",
					"symbol": "N",
					"nr": 84,
					"metro": false,
					"express": false,
					"night": true
				}
			]
		},
		"when": "2018-07-01T15:58:00.000+02:00",
		"direction": "U Friedrich-Wilhelm-Platz",
		"line": {
			"type": "line",
			"id": "bus-246",
			"name": "246",
			"public": true,
			"class": 8,
			"productCode": 3,
			"operator": {
				"type": "operator",
				"id": "berliner-verkehrsbetriebe",
				"name": "Berliner Verkehrsbetriebe"
			},
			"product": "bus",
			"mode": "bus",
			"symbol": null,
			"nr": 246,
			"metro": false,
			"express": false,
			"night": false
		},
		"remarks": [],
		"trip": 59206,
		"delay": 480
	},
	{
		"journeyId": "1|53630|5|86|1072018",
		"station": {
			"type": "station",
			"id": "900000068353",
			"name": "Friedrich-Wilhelm-Str.",
			"location": {
				"type": "location",
				"latitude": 52.458431,
				"longitude": 13.376129
			},
			"products": {
				"suburban": true,
				"subway": true,
				"tram": true,
				"bus": true,
				"ferry": false,
				"express": false,
				"regional": false
			},
			"lines": [
				{
					"type": "line",
					"id": "bus-184",
					"name": "184",
					"public": true,
					"class": 8,
					"product": "bus",
					"mode": "bus",
					"symbol": null,
					"nr": 184,
					"metro": false,
					"express": false,
					"night": false
				},
				{
					"type": "line",
					"id": "bus-246",
					"name": "246",
					"public": true,
					"class": 8,
					"product": "bus",
					"mode": "bus",
					"symbol": null,
					"nr": 246,
					"metro": false,
					"express": false,
					"night": false
				},
				{
					"type": "line",
					"id": "bus-n84",
					"name": "N84",
					"public": true,
					"class": 8,
					"product": "bus",
					"mode": "bus",
					"symbol": "N",
					"nr": 84,
					"metro": false,
					"express": false,
					"night": true
				}
			]
		},
		"when": "2018-07-01T15:58:00.000+02:00",
		"direction": "Lichterfelde, Lindenstr.",
		"line": {
			"type": "line",
			"id": "bus-184",
			"name": "184",
			"public": true,
			"class": 8,
			"productCode": 3,
			"operator": {
				"type": "operator",
				"id": "berliner-verkehrsbetriebe",
				"name": "Berliner Verkehrsbetriebe"
			},
			"product": "bus",
			"mode": "bus",
			"symbol": null,
			"nr": 184,
			"metro": false,
			"express": false,
			"night": false
		},
		"remarks": [],
		"trip": 53630,
		"delay": 180
	},
	{
		"journeyId": "1|53634|4|86|1072018",
		"station": {
			"type": "station",
			"id": "900000068353",
			"name": "Friedrich-Wilhelm-Str.",
			"location": {
				"type": "location",
				"latitude": 52.458431,
				"longitude": 13.376129
			},
			"products": {
				"suburban": true,
				"subway": true,
				"tram": true,
				"bus": true,
				"ferry": false,
				"express": false,
				"regional": false
			},
			"lines": [
				{
					"type": "line",
					"id": "bus-184",
					"name": "184",
					"public": true,
					"class": 8,
					"product": "bus",
					"mode": "bus",
					"symbol": null,
					"nr": 184,
					"metro": false,
					"express": false,
					"night": false
				},
				{
					"type": "line",
					"id": "bus-246",
					"name": "246",
					"public": true,
					"class": 8,
					"product": "bus",
					"mode": "bus",
					"symbol": null,
					"nr": 246,
					"metro": false,
					"express": false,
					"night": false
				},
				{
					"type": "line",
					"id": "bus-n84",
					"name": "N84",
					"public": true,
					"class": 8,
					"product": "bus",
					"mode": "bus",
					"symbol": "N",
					"nr": 84,
					"metro": false,
					"express": false,
					"night": true
				}
			]
		},
		"when": "2018-07-01T16:02:00.000+02:00",
		"direction": "S+U Tempelhof",
		"line": {
			"type": "line",
			"id": "bus-184",
			"name": "184",
			"public": true,
			"class": 8,
			"productCode": 3,
			"operator": {
				"type": "operator",
				"id": "berliner-verkehrsbetriebe",
				"name": "Berliner Verkehrsbetriebe"
			},
			"product": "bus",
			"mode": "bus",
			"symbol": null,
			"nr": 184,
			"metro": false,
			"express": false,
			"night": false
		},
		"remarks": [],
		"trip": 53634,
		"delay": 60
	}
]
```

**Comment by derhuerst** [comment]
@deg0nz 

- Please send an identifier all the time. You may send different ones if you're testing though. https://github.com/deg0nz/MMM-PublicTransportBerlin/blob/390b60d65a5749bd4c0844789ece3a097d6e4880/VbbFetcher.js#L49
- You might want to display canceled departures as well. https://github.com/deg0nz/MMM-PublicTransportBerlin/blob/390b60d65a5749bd4c0844789ece3a097d6e4880/VbbFetcher.js#L74
- Sort `Date` objects directly (by converting to numbers) instead of using `getTime()`. It will fail at midnight. https://github.com/deg0nz/MMM-PublicTransportBerlin/blob/390b60d65a5749bd4c0844789ece3a097d6e4880/VbbFetcher.js#L97-L98

But from looking at the code in `VbbFetcher.js`, I can't see how the above bugs might appear.

**Comment by ferby09** [comment]
@derhuerst, Maybe you should create a new branch from the working code on your server and let @juliuste use that instead. This would at least rule out the possibility of a crucial change in the code as the main reason for this problem.

**Comment by derhuerst** [comment]
I had deployed `2` before. @juliuste has as well AFAIK. So that shouldn't be an issue.

**Comment by rejas** [comment]
was the "name" field for busses always a single string? looking at the MMM-PTB code I see a split command that now seems to be the culprit:
https://github.com/deg0nz/MMM-PublicTransportBerlin/blob/390b60d65a5749bd4c0844789ece3a097d6e4880/MMM-PublicTransportBerlin.js#L406

**Comment by juliuste** [comment]
> was the "name" field for busses always a single string? looking at the MMM-PTB code I see a split command that now seems to be the culprit

@derhuerst Could it be that updated a dependency of the VBB REST API that handles line parsing which in turn changed the line names from `Bus 184` -> `184`. *In-range* dependency updates could explain why "my" endpoint might give different results to yours.

**Comment by derhuerst** [comment]
@juliuste Yes, [you're right](https://github.com/public-transport/hafas-client/blame/8923bcb6194bd927cfd3e984b573d07d60c0523e/p/vbb/index.js#L45).

@deg0nz I think the way forward is to remove special `line.name` handling an strip "Bus " etc. up the chain, e.g. in `hafas-client`.

**Comment by ferby09** [comment]
The module is working again thanks to several mirrors hosted at now.sh, but this problem persists. So @deg0nz, could you please try to implement the changes suggested above?

**Comment by derhuerst** [comment]
No wait! I'll soon set up the mirrored API, but I haven't yet.

**Comment by deg0nz** [comment]
@ferby09 I'll implement this eventually. Just don't know when there's time to do it.

And I'll wait for @derhuerst to complete the new setup.

**Comment by deg0nz** [comment]
#34 Should solve this issue. Thanks to @rejas again!

I reopen this issue to remind me that I wanted to implement the hints by @derhuerst. Will close this afterwards.

**Comment by deg0nz** [comment]
11a2f93 implemets the hints. Closing.

**Comment by derhuerst** [comment]
FYI:

- I have set up [`v5.vbb.transport.rest`](https://v5.vbb.transport.rest/), which has slightly more intuitive route names and documentation.
- I have opened https://github.com/public-transport/transport.rest/issues/2 for the long-term perspective of these APIs.
