### ISSUE TITLE
directionStationId not working

### ISSUE THREAD

**Issue by ferby09** [deg0nz/MMM-PublicTransportBerlin#39]
First of all thank you again for your hard work in cooperation with @derhuerst and making this module usable again.
Unfortunately I can't get the directionStationId to work like it did with vbb-rest. The IDs are the same with bvg-rest, but it isn't working as I can still see the lines in the other direction.
Is this an issue in bvg-rest?

**Comment by ferby09** [comment]
Thank you for your quick response, I'll have a look. But I can't remember having issues with it when you were still using the vbb-client.

**Comment by deg0nz** [comment]
Alright, then I‘ll try to find time this weekend to look into it.

Von meinem Mobiltelefon gesendet. B.

**Comment by deg0nz** [comment]
Commit 6319c4508772898aac072bb8da807aef0a535000 should fix this issue. The code used the old `nextStation` parameter which was changed to `direction` I think.

@ferby09 Could you please check if this works for you and close the issue afterwards?

**Comment by deg0nz** [comment]
As I'm playing around a little bit... `nextStation` still gives answers.. and the amount of returned station differs from `direction`.

@derhuerst: What is the difference between these two?

**Comment by derhuerst** [comment]
It's an obscure technical one: [`direction` uses a HAFAS parameter and therefore returns whatever HAFAS understands by "in direction"; `nextStation` uses `hafas-departures-in-direction`, which queries enough departures and then filters those that actually pass by the stop/station.](https://github.com/derhuerst/hafas-rest-api/blob/bb6d60759971770fac6fa3fe500d84ac5daac0d1/routes/departures.js#L33-L55)

I don't know exactly which is the better one. I have also forgotten wether all HAFAS endpoints support the `direction` parameter (then `nextStation` should be used), but BVG does AFAIR.

So please play with `direction`, using a few edge cases:

- Is it always the *next* station or *any* along the trip?
- What about [split-up stations such as Alexanderplatz](https://derhuerst.github.io/merge-vbb-stations/)?

**Comment by deg0nz** [comment]
@ferby09 Any updates?

**Comment by ferby09** [comment]
I'm sorry for my late reply but I was kind of busy because my Magic Mirror's power supply was malfunctioning so I couldn't test it until now.
It works perfectly fine now, thank you very much!

**Comment by derhuerst** [comment]
Please document your findings here!
