### ISSUE TITLE
excludeDelayFromTimeLabel not working

### ISSUE THREAD

**Issue by bertbln** [deg0nz/MMM-PublicTransportBerlin#40]
Hello, I think the Option "excludeDelayFromTimeLabel" is not working

**Comment by bertbln** [comment]
SORRY!  It was my fault... I thought the time difference would not appear in the table, it works korrekt!
Thanks for this nice piece of software!

**Comment by deg0nz** [comment]
Ahh, so you wanted to have the realtime information removed from the table?
