### ISSUE TITLE
The module is not working

### ISSUE THREAD

**Issue by mip44** [deg0nz/MMM-PublicTransportBerlin#47]
Hi, I have some troubles with this module.

I installed it correctly with the given commands and I can also see the Folder.
Then I copied the example (alexander Platz) into the Magic mirror config where all the other modules are.
When I start MM nothing happens, all other modules load smoothly, but not the transportation module, not even an error message. It’s just like the code of this module isn’t there but I double checked everything.
Did I something wrong?

thank already for the replys!

**Comment by AtzeTRue** [comment]
No u didn't. I've got the same problem, no resolution.

**Comment by AtzeTRue** [comment]
No u didn't. I've got the same problem, no resolution.

**Comment by deg0nz** [comment]
Hi, sorry for the delayed reply, I‘m on holidays right now...

You did realize, that there is a lot of dummy data in the example config? This one is actually for demonstrating all the possible options. Maybe I should add another example config to the readme with working data in it...

Can you please try to use a minimal config first? Maybe just add the station ID and the module position (all the necessary data is present in the default config). 

And if this works, add the parameters you need incrementally.

Alternatively: Use the default config from the MMM-PublicTransportBerlin.js and adjust it to your needs. This one should be working.

**Comment by AtzeTRue** [comment]
Oh that work's for me, thank you very much, great job!

**Comment by deg0nz** [comment]
@mip44 is the issue solved for you as well? I would like to close this issue.

**Comment by mip44** [comment]
sorry for the late response and thanks, yes it is working now.

**Comment by deg0nz** [comment]
@mip44 That's good news :)
I'm closing this now.
