### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by fry0815** [deg0nz/MMM-PublicTransportBerlin#5]
There is a display error, if the type of the train is e.g. "ICE, IC, LOC, EC".  
They are displayed as "undefined" or "LOCOMORE" with yellow background.
Look at this example of ICE|EC
![ice ec](https://cloud.githubusercontent.com/assets/5508344/22066864/3547336e-dd8f-11e6-8fbc-0294f941759a.png)
or this example of LOC (what ever this is o.O)
![loc](https://cloud.githubusercontent.com/assets/5508344/22066865/354b7276-dd8f-11e6-943c-f95d9403f526.png)

**Comment by deg0nz** [comment]
I'll try to look into this in the next days. Can't promise it though.

**Comment by fry0815** [comment]
Hi, maybe i fixed that. I test it in the next days. If it's fine, you get a PR.
And "LOCOMORE" is not a bug, it's an new line...

**Comment by deg0nz** [comment]
Since PR #13 fixed this issue, I'm closing this now.

Thanks for your work @fry0815!
