### ISSUE TITLE
make changes in design? size, color, brightness and more? 

### ISSUE THREAD

**Issue by VinceBln** [deg0nz/MMM-PublicTransportBerlin#69]
**Is it possible to edit the font and size? How can you change the color and brightness of the symbols (depature, label, direction).**

I am glad about every answer :)

With kind regards
Vincent

**Comment by deg0nz** [comment]
Currently it is not possible to change this stuff. The module uses the global configuration of the mirror for font sizes and colors.

What exactly do you want to achieve? / What is the exact problem?

The colors for the line symbols are the original color codes for the respective lines (mostly taken from Wikipedia).

You would have to change the values in the CSS file of the module. There is also an option to disable colors of you want a monochrome module.

**Comment by VinceBln** [comment]
The problem is, once the glass is on, you can hardly recognize the gray icons and texts...
What can be done about the problem? 

You can see the problem in the picture
![IMG_2384](https://user-images.githubusercontent.com/99336496/153212823-3d5e253c-8a8a-49a2-9faa-57579aeff22f.jpg)

**Comment by VinceBln** [comment]
and can you edit the width of the tables? to make them equal..
thank you

**Comment by KristjanESPERANTO** [comment]
In your custom.css you could do something like that:

```
/* Width of the modules left and right */
.region.left,
.region.right {
  max-width: 25vw;
  min-width: 25vw;
}

/* Color of the symbols in the head of MMM-PublicTransportBerlin */
.ptbTable thead tr {
  color: white;
}
```
Depending on your resolution it could look like this:
![Ekrankopio de 2022-02-09 19-52-32](https://user-images.githubusercontent.com/35647502/153269973-8d2e0359-9bff-419b-9a97-d9a47745a488.png)

**Comment by deg0nz** [comment]
The provided solution by @KristjanESPERANTO is the way to go.

@VinceBln Follow the insructions for custom CSS and adjust as needed: https://docs.magicmirror.builders/modules/customcss.html

**Comment by deg0nz** [comment]
I assume, the isue is solved. Please feel free to reopen if the problems still exist.
