### ISSUE TITLE
S-Bahn departures in Region Hannover not displayed

### ISSUE THREAD

**Issue by Sinned80** [deg0nz/MMM-PublicTransportBerlin#9]
Hi,

it seems that the S-Bahn departures in REgion Hannover are loaded by the backend but not displayed ín the list on MagicMirror.

I've checked this for Barsinghausen (station ID 8000812) and Egestorf(Deister) (station ID 8001675). Bus departures are correcly displayed (both stations handle bus and S-Bahn; not more)

After enabling lines 69+70 in DbFetcher.js the console shows this
Parsing: Bus 501 nach Sporthotel um Wed Mar 22 2017 16:31:00 GMT+0100 (CET)
Parsing: Bus 502 nach Worthstraße um Wed Mar 22 2017 16:31:00 GMT+0100 (CET)

Parsing: S 2 nach Haste um Wed Mar 22 2017 16:42:00 GMT+0100 (CET)
(node:2333) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'type' of undefined

**Comment by deg0nz** [comment]
Hey @Sinned80 I think, your Issue is wrong here. You should issue it to [https://github.com/olexs/MMM-PublicTransportDB](https://github.com/olexs/MMM-PublicTransportDB).

...but I see the last commit of his module seems to fix your issue. All good :)
